import pandas as pd
import os
from pandas.testing import assert_frame_equal
import unittest
from datetime import datetime

from real_estate_madrid.functions.save_data_to_csv import (
    backup_idealista_data,
    append_idealista_data,
    remove_duplicates_from_csv,
)
from real_estate_madrid.utils.global_variables import TEST_DATA_DIRECTORY


class TestSaveDataToCsv(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.data_directory = TEST_DATA_DIRECTORY
        cls.file_name_idealista_data = "idealista_data.csv"
        cls.file_path_idealista_data = os.path.join(
            cls.data_directory, cls.file_name_idealista_data
        )
        cls.file_path_idealista_data_backup = os.path.join(
            cls.data_directory + "idealista_data_backups/",
            cls.file_name_idealista_data.strip(".csv")
            + "_backup_"
            + datetime.today().strftime("%Y-%m-%d")
            + ".csv",
        )

        df = pd.DataFrame(
            columns=[
                "propertyCode",
                "thumbnail",
                "externalReference",
                "numPhotos",
                "floor",
                "price",
                "propertyType",
                "operation",
                "size",
                "exterior",
                "rooms",
                "bathrooms",
                "address",
                "province",
                "municipality",
                "district",
                "country",
                "neighborhood",
                "latitude",
                "longitude",
                "showAddress",
                "url",
                "distance",
                "description",
                "hasVideo",
                "status",
                "newDevelopment",
                "hasLift",
                "parkingSpace",
                "priceByArea",
                "detailedType",
                "suggestedTexts",
                "hasPlan",
                "has3DTour",
                "has360",
                "hasStaging",
                "topNewDevelopment",
                "superTopHighlight",
                "labels",
                "highlight",
            ],
            data=[
                [
                    "123456678",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1500.0,
                    "flat",
                    "rent",
                    70.0,
                    True,
                    1,
                    1,
                    "Calle Argumosa",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Lavapiés-Embajadores",
                    40.410107,
                    -3.696234,
                    False,
                    "https://www.idealista.com/inmueble/123456678/",
                    969,
                    "¡PRECIOSO apartamento EN PLENO CORAZÓN DE MADR...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    21.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Lavapiés-Embajadores, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
                [
                    "123456644",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1200.0,
                    "flat",
                    "rent",
                    60.0,
                    True,
                    1,
                    1,
                    "Calle Ejemplo",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Lavapiés-Embajadores",
                    40.410107,
                    -3.696234,
                    False,
                    "https://www.idealista.com/inmueble/123456678/",
                    969,
                    "¡PMuy buena oportunidad...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    21.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Lavapiés-Embajadores, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
                [
                    "123456678",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1500.0,
                    "flat",
                    "rent",
                    70.0,
                    True,
                    1,
                    1,
                    "Calle Argumosa",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Lavapiés-Embajadores",
                    40.410107,
                    -3.696234,
                    False,
                    "https://www.idealista.com/inmueble/123456678/",
                    969,
                    "¡PRECIOSO apartamento EN PLENO CORAZÓN DE MADR...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    21.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Lavapiés-Embajadores, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
            ],
        )

        df.to_csv(cls.file_path_idealista_data, index=False)

        cls.df_to_append = pd.DataFrame(
            columns=[
                "propertyCode",
                "thumbnail",
                "externalReference",
                "numPhotos",
                "floor",
                "price",
                "propertyType",
                "operation",
                "size",
                "exterior",
                "rooms",
                "bathrooms",
                "address",
                "province",
                "municipality",
                "district",
                "country",
                "neighborhood",
                "latitude",
                "longitude",
                "showAddress",
                "url",
                "distance",
                "description",
                "hasVideo",
                "status",
                "newDevelopment",
                "hasLift",
                "parkingSpace",
                "priceByArea",
                "detailedType",
                "suggestedTexts",
                "hasPlan",
                "has3DTour",
                "has360",
                "hasStaging",
                "topNewDevelopment",
                "superTopHighlight",
                "labels",
                "highlight",
            ],
            data=[
                [
                    "123456655",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1550.0,
                    "flat",
                    "rent",
                    72.0,
                    True,
                    1,
                    1,
                    "Gran Vía",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Centro",
                    40.123,
                    -3.098,
                    False,
                    "https://www.idealista.com/inmueble/123456655/",
                    700,
                    "¡MUY CENTRAL...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    25.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Centro, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ]
            ],
        )

    @classmethod
    def tearDownClass(cls):
        os.remove(cls.file_path_idealista_data)
        os.remove(cls.file_path_idealista_data_backup)

    def test_backup_idealista_data(self):
        """TestSaveDataToCsv 1: Test function backup_idealista_data"""
        backup_idealista_data(
            file_name=self.file_name_idealista_data,
            data_dir=TEST_DATA_DIRECTORY,
        )
        original = pd.read_csv(self.file_path_idealista_data)
        backup = pd.read_csv(self.file_path_idealista_data_backup)

        assert_frame_equal(original, backup)

    def test_append_idealista_data(self):
        """TestSaveDataToCsv 2: Test function  append_idealista_data"""
        append_idealista_data(
            file_name=self.file_name_idealista_data,
            df_new_data=self.df_to_append,
            data_dir=TEST_DATA_DIRECTORY,
        )
        df_appended = pd.read_csv(
            self.file_path_idealista_data,
            dtype={"propertyCode": object, "externalReference": object},
        ).fillna("")
        df_test = pd.DataFrame(
            columns=[
                "propertyCode",
                "thumbnail",
                "externalReference",
                "numPhotos",
                "floor",
                "price",
                "propertyType",
                "operation",
                "size",
                "exterior",
                "rooms",
                "bathrooms",
                "address",
                "province",
                "municipality",
                "district",
                "country",
                "neighborhood",
                "latitude",
                "longitude",
                "showAddress",
                "url",
                "distance",
                "description",
                "hasVideo",
                "status",
                "newDevelopment",
                "hasLift",
                "parkingSpace",
                "priceByArea",
                "detailedType",
                "suggestedTexts",
                "hasPlan",
                "has3DTour",
                "has360",
                "hasStaging",
                "topNewDevelopment",
                "superTopHighlight",
                "labels",
                "highlight",
            ],
            data=[
                [
                    "123456678",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1500.0,
                    "flat",
                    "rent",
                    70.0,
                    True,
                    1,
                    1,
                    "Calle Argumosa",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Lavapiés-Embajadores",
                    40.410107,
                    -3.696234,
                    False,
                    "https://www.idealista.com/inmueble/123456678/",
                    969,
                    "¡PRECIOSO apartamento EN PLENO CORAZÓN DE MADR...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    21.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Lavapiés-Embajadores, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
                [
                    "123456644",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1200.0,
                    "flat",
                    "rent",
                    60.0,
                    True,
                    1,
                    1,
                    "Calle Ejemplo",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Lavapiés-Embajadores",
                    40.410107,
                    -3.696234,
                    False,
                    "https://www.idealista.com/inmueble/123456678/",
                    969,
                    "¡PMuy buena oportunidad...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    21.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Lavapiés-Embajadores, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
                [
                    "123456678",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1500.0,
                    "flat",
                    "rent",
                    70.0,
                    True,
                    1,
                    1,
                    "Calle Argumosa",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Lavapiés-Embajadores",
                    40.410107,
                    -3.696234,
                    False,
                    "https://www.idealista.com/inmueble/123456678/",
                    969,
                    "¡PRECIOSO apartamento EN PLENO CORAZÓN DE MADR...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    21.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Lavapiés-Embajadores, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
                [
                    "123456655",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1550.0,
                    "flat",
                    "rent",
                    72.0,
                    True,
                    1,
                    1,
                    "Gran Vía",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Centro",
                    40.123,
                    -3.098,
                    False,
                    "https://www.idealista.com/inmueble/123456655/",
                    700,
                    "¡MUY CENTRAL...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    25.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Centro, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
            ],
        )
        assert_frame_equal(df_appended, df_test)

    def test_remove_duplicates(self):
        """TestSaveDataToCsv 3: Test function  remove_duplicates"""
        # append the same line twice
        append_idealista_data(
            file_name=self.file_name_idealista_data,
            df_new_data=self.df_to_append,
            data_dir=TEST_DATA_DIRECTORY,
        )
        append_idealista_data(
            file_name=self.file_name_idealista_data,
            df_new_data=self.df_to_append,
            data_dir=TEST_DATA_DIRECTORY,
        )
        # remove duplicate lines
        remove_duplicates_from_csv(
            file_name=self.file_name_idealista_data,
            data_dir=TEST_DATA_DIRECTORY,
        )
        df_dedup = pd.read_csv(
            self.file_path_idealista_data,
            dtype={"propertyCode": object, "externalReference": object},
        ).fillna("")

        df_test = pd.DataFrame(
            columns=[
                "propertyCode",
                "thumbnail",
                "externalReference",
                "numPhotos",
                "floor",
                "price",
                "propertyType",
                "operation",
                "size",
                "exterior",
                "rooms",
                "bathrooms",
                "address",
                "province",
                "municipality",
                "district",
                "country",
                "neighborhood",
                "latitude",
                "longitude",
                "showAddress",
                "url",
                "distance",
                "description",
                "hasVideo",
                "status",
                "newDevelopment",
                "hasLift",
                "parkingSpace",
                "priceByArea",
                "detailedType",
                "suggestedTexts",
                "hasPlan",
                "has3DTour",
                "has360",
                "hasStaging",
                "topNewDevelopment",
                "superTopHighlight",
                "labels",
                "highlight",
            ],
            data=[
                [
                    "123456678",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1500.0,
                    "flat",
                    "rent",
                    70.0,
                    True,
                    1,
                    1,
                    "Calle Argumosa",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Lavapiés-Embajadores",
                    40.410107,
                    -3.696234,
                    False,
                    "https://www.idealista.com/inmueble/123456678/",
                    969,
                    "¡PRECIOSO apartamento EN PLENO CORAZÓN DE MADR...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    21.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Lavapiés-Embajadores, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
                [
                    "123456644",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1200.0,
                    "flat",
                    "rent",
                    60.0,
                    True,
                    1,
                    1,
                    "Calle Ejemplo",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Lavapiés-Embajadores",
                    40.410107,
                    -3.696234,
                    False,
                    "https://www.idealista.com/inmueble/123456678/",
                    969,
                    "¡PMuy buena oportunidad...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    21.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Lavapiés-Embajadores, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
                [
                    "123456655",
                    "https://img3.idealista.com/blur/WEB_LISTING/0/",
                    "",
                    9,
                    1,
                    1550.0,
                    "flat",
                    "rent",
                    72.0,
                    True,
                    1,
                    1,
                    "Gran Vía",
                    "Madrid",
                    "Madrid",
                    "Centro",
                    "es",
                    "Centro",
                    40.123,
                    -3.098,
                    False,
                    "https://www.idealista.com/inmueble/123456655/",
                    700,
                    "¡MUY CENTRAL...",
                    False,
                    "good",
                    False,
                    True,
                    "",
                    25.0,
                    "{'typology': 'flat'}",
                    "{'subtitle': 'Centro, Madrid'}",
                    False,
                    False,
                    False,
                    False,
                    False,
                    False,
                    "",
                    "",
                ],
            ],
        )

        assert_frame_equal(df_dedup, df_test)
