name: Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniconda
      run: |
        MINICONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
        curl -o miniconda.sh $MINICONDA_URL
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda init bash
      shell: bash

    - name: Create Conda environment
      run: conda create -n myenv python=3.11.5
      shell: bash

    - name: Activate Conda environment
      run: source $HOME/miniconda/etc/profile.d/conda.sh && conda activate myenv
      shell: bash

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      shell: bash
    - name: Run pylint
      run: |
        pylint $(git ls-files '*.py') --disable=C --max-line-length=120 --disable=R0913,R0914
