name: Pylint

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.5
        
    - name: Install dependencies
      run: |
        ${{ env.pythonLocation }}/python.exe -m pip install --upgrade pip
        ${{ env.pythonLocation }}/python.exe -m pip install -r requirements.txt
        
    - name: Analysing the code with pylint
      run: |
        $env:PYTHONPATH = ${{ github.workspace }}
        echo "PYTHONPATH IS $env:PYTHONPATH"
        Get-ChildItem -Path $env:PYTHONPATH -Recurse -Filter "*.py" | ForEach-Object { pylint $_.FullName --disable=C --max-line-length=120 --disable=R0913,R0914 }
