name: Run Unit Tests

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.5

    - name: Install dependencies
      run: |
        ${{ env.pythonLocation }}\python.exe -m pip install --upgrade pip
        ${{ env.pythonLocation }}\python.exe -m pip install -r requirements.txt

    - name: Set pythonpath
      run: |
        echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV
        echo ${{ github.workspace }}
  
    - name: Print pythonpath
      run: |
        echo "PYTHONPATH IS $PYTHONPATH"
  
    - name: Run unittests
      run: |
        cd ..
        python -m unittest discover -v real-estate-madrid

    - name: Check test results and prevent push on failure
      if: ${{ failure() }}
      run: exit 1
